#!/usr/bin/env python

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

xm = np.load('xm.npy')
x = np.load('x.npy')

A1m = np.load('TERRA_A_test1_mean.npy')
A1v = np.load('TERRA_A_test1_vars.npy')
A1r = np.load('TERRA_A_test1_rate.npy')
B1m = np.load('TERRA_B_test1_mean.npy')
B1v = np.load('TERRA_B_test1_vars.npy')
B1r = np.load('TERRA_B_test1_rate.npy')

A2m = np.load('TERRA_A_test2_mean.npy')
A2v = np.load('TERRA_A_test2_vars.npy')
A2r = np.load('TERRA_A_test2_rate.npy')
B2m = np.load('TERRA_B_test2_mean.npy')
B2v = np.load('TERRA_B_test2_vars.npy')
B2r = np.load('TERRA_B_test2_rate.npy')

A3m = np.load('TERRA_A_test3_mean.npy')
A3v = np.load('TERRA_A_test3_vars.npy')
A3r = np.load('TERRA_A_test3_rate.npy')
B3m = np.load('TERRA_B_test3_mean.npy')
B3v = np.load('TERRA_B_test3_vars.npy')
B3r = np.load('TERRA_B_test3_rate.npy')

A4m = np.load('TERRA_A_test4_mean.npy')
A4v = np.load('TERRA_A_test4_vars.npy')
A4r = np.load('TERRA_A_test4_rate.npy')
B4m = np.load('TERRA_B_test4_mean.npy')
B4v = np.load('TERRA_B_test4_vars.npy')
B4r = np.load('TERRA_B_test4_rate.npy')

A5m = np.load('TERRA_A_test5_mean.npy')
A5v = np.load('TERRA_A_test5_vars.npy')
A5r = np.load('TERRA_A_test5_rate.npy')
B5m = np.load('TERRA_B_test5_mean.npy')
B5v = np.load('TERRA_B_test5_vars.npy')
B5r = np.load('TERRA_B_test5_rate.npy')

A6m = np.load('TERRA_A_test6_mean.npy')
A6v = np.load('TERRA_A_test6_vars.npy')
A6r = np.load('TERRA_A_test6_rate.npy')
B6m = np.load('TERRA_B_test6_mean.npy')
B6v = np.load('TERRA_B_test6_vars.npy')
B6r = np.load('TERRA_B_test6_rate.npy')

A7m = np.load('TERRA_A_test7_mean.npy')
A7v = np.load('TERRA_A_test7_vars.npy')
A7r = np.load('TERRA_A_test7_rate.npy')
B7m = np.load('TERRA_B_test7_mean.npy')
B7v = np.load('TERRA_B_test7_vars.npy')
B7r = np.load('TERRA_B_test7_rate.npy')

x1 = np.arange(A1m.shape[0])*100*6.38*1e-3
x2 = np.arange(A2m.shape[0])*100*6.38*1e-3
x3 = np.arange(A3m.shape[0])*100*6.38*1e-3
x4 = np.arange(A4m.shape[0])*100*6.38*1e-3
x5 = np.arange(A5m.shape[0])*100*6.38*1e-3
x6 = np.arange(A6m.shape[0])*100*6.38*1e-3
x7 = np.arange(A7m.shape[0])*100*6.38*1e-3

fig, ax = plt.subplots(2,3,sharex=True,sharey=True)
ax[0,0].pcolormesh(x1,xm,A1m.T,cmap='jet',vmin=0,vmax=80)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Fiber A')
ax[0,1].pcolormesh(x1,xm,A1v.T,cmap='hot_r',vmin=1,vmax=100)
ax[0,1].set_title('Var. PSD')
ax[0,2].pcolormesh(x1,xm,A1r.T,cmap='jet',vmin=30,vmax=60)
ax[0,2].set_title('Mean PSD (rel. 1/f)')
ax[1,0].pcolormesh(x1,xm,B1m.T,cmap='jet',vmin=0,vmax=80)
ax[1,0].set_ylabel('Fiber B')
ax[1,0].set_xlabel('Distance (km)')
ax[1,1].pcolormesh(x1,xm,B1v.T,cmap='hot_r',vmin=1,vmax=100)
ax[1,1].set_xlabel('Distance (km)')
ax[1,2].pcolormesh(x1,xm,B1r.T,cmap='jet',vmin=30,vmax=60)
ax[1,2].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.suptitle('TERRA-SW Test 1 (10 m pulse, 17 m gauge)')
plt.tight_layout()
plt.savefig('TERRA_summary_1.png')

fig, ax = plt.subplots(2,3,sharex=True,sharey=True)
ax[0,0].pcolormesh(x2,xm,A2m.T,cmap='jet',vmin=0,vmax=80)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Fiber A')
ax[0,1].pcolormesh(x2,xm,A2v.T,cmap='hot_r',vmin=1,vmax=100)
ax[0,1].set_title('Var. PSD')
ax[0,2].pcolormesh(x2,xm,A2r.T,cmap='jet',vmin=30,vmax=60)
ax[0,2].set_title('Mean PSD (rel. 1/f)')
ax[1,0].pcolormesh(x2,xm,B2m.T,cmap='jet',vmin=0,vmax=80)
ax[1,0].set_ylabel('Fiber B')
ax[1,0].set_xlabel('Distance (km)')
ax[1,1].pcolormesh(x2,xm,B2v.T,cmap='hot_r',vmin=1,vmax=100)
ax[1,1].set_xlabel('Distance (km)')
ax[1,2].pcolormesh(x2,xm,B2r.T,cmap='jet',vmin=30,vmax=60)
ax[1,2].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.suptitle('TERRA-SW Test 2 (13 m pulse, 18 m gauge)')
plt.tight_layout()
plt.savefig('TERRA_summary_2.png')

fig, ax = plt.subplots(2,3,sharex=True,sharey=True)
ax[0,0].pcolormesh(x3,xm,A3m.T,cmap='jet',vmin=0,vmax=80)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Fiber A')
ax[0,1].pcolormesh(x3,xm,A3v.T,cmap='hot_r',vmin=1,vmax=100)
ax[0,1].set_title('Var. PSD')
ax[0,2].pcolormesh(x3,xm,A3r.T,cmap='jet',vmin=30,vmax=60)
ax[0,2].set_title('Mean PSD (rel. 1/f)')
ax[1,0].pcolormesh(x3,xm,B3m.T,cmap='jet',vmin=0,vmax=80)
ax[1,0].set_ylabel('Fiber B')
ax[1,0].set_xlabel('Distance (km)')
ax[1,1].pcolormesh(x3,xm,B3v.T,cmap='hot_r',vmin=1,vmax=100)
ax[1,1].set_xlabel('Distance (km)')
ax[1,2].pcolormesh(x3,xm,B3r.T,cmap='jet',vmin=30,vmax=60)
ax[1,2].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.suptitle('TERRA-SW Test 3 (15 m pulse, 21 m gauge)')
plt.tight_layout()
plt.savefig('TERRA_summary_3.png')

fig, ax = plt.subplots(2,3,sharex=True,sharey=True)
ax[0,0].pcolormesh(x4,xm,A4m.T,cmap='jet',vmin=0,vmax=80)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Fiber A')
ax[0,1].pcolormesh(x4,xm,A4v.T,cmap='hot_r',vmin=1,vmax=100)
ax[0,1].set_title('Var. PSD')
ax[0,2].pcolormesh(x4,xm,A4r.T,cmap='jet',vmin=30,vmax=60)
ax[0,2].set_title('Mean PSD (rel. 1/f)')
ax[1,0].pcolormesh(x4,xm,B4m.T,cmap='jet',vmin=0,vmax=80)
ax[1,0].set_ylabel('Fiber B')
ax[1,0].set_xlabel('Distance (km)')
ax[1,1].pcolormesh(x4,xm,B4v.T,cmap='hot_r',vmin=1,vmax=100)
ax[1,1].set_xlabel('Distance (km)')
ax[1,2].pcolormesh(x4,xm,B4r.T,cmap='jet',vmin=30,vmax=60)
ax[1,2].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.suptitle('TERRA-SW Test 4 (17 m pulse, 24 m gauge)')
plt.tight_layout()
plt.savefig('TERRA_summary_4.png')

fig, ax = plt.subplots(2,3,sharex=True,sharey=True)
ax[0,0].pcolormesh(x5,xm,A5m.T,cmap='jet',vmin=0,vmax=80)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Fiber A')
ax[0,1].pcolormesh(x5,xm,A5v.T,cmap='hot_r',vmin=1,vmax=100)
ax[0,1].set_title('Var. PSD')
ax[0,2].pcolormesh(x5,xm,A5r.T,cmap='jet',vmin=30,vmax=60)
ax[0,2].set_title('Mean PSD (rel. 1/f)')
ax[1,0].pcolormesh(x5,xm,B5m.T,cmap='jet',vmin=0,vmax=80)
ax[1,0].set_ylabel('Fiber B')
ax[1,0].set_xlabel('Distance (km)')
ax[1,1].pcolormesh(x5,xm,B5v.T,cmap='hot_r',vmin=1,vmax=100)
ax[1,1].set_xlabel('Distance (km)')
ax[1,2].pcolormesh(x5,xm,B5r.T,cmap='jet',vmin=30,vmax=60)
ax[1,2].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.suptitle('TERRA-SW Test 5 (7.5 m pulse, 14 m gauge)')
plt.tight_layout()
plt.savefig('TERRA_summary_5.png')

fig, ax = plt.subplots(2,3,sharex=True,sharey=True)
ax[0,0].pcolormesh(x6,xm,A6m.T,cmap='jet',vmin=0,vmax=80)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Fiber A')
ax[0,1].pcolormesh(x6,xm,A6v.T,cmap='hot_r',vmin=1,vmax=100)
ax[0,1].set_title('Var. PSD')
ax[0,2].pcolormesh(x6,xm,A6r.T,cmap='jet',vmin=30,vmax=60)
ax[0,2].set_title('Mean PSD (rel. 1/f)')
ax[1,0].pcolormesh(x6,xm,B6m.T,cmap='jet',vmin=0,vmax=80)
ax[1,0].set_ylabel('Fiber B')
ax[1,0].set_xlabel('Distance (km)')
ax[1,1].pcolormesh(x6,xm,B6v.T,cmap='hot_r',vmin=1,vmax=100)
ax[1,1].set_xlabel('Distance (km)')
ax[1,2].pcolormesh(x6,xm,B6r.T,cmap='jet',vmin=30,vmax=60)
ax[1,2].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.suptitle('TERRA-SW Test 6 (5 m pulse, 9.6 m gauge)')
plt.tight_layout()
plt.savefig('TERRA_summary_6.png')

fig, ax = plt.subplots(2,3,sharex=True,sharey=True)
ax[0,0].pcolormesh(x7,xm,A7m.T,cmap='jet',vmin=0,vmax=80)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Fiber A')
ax[0,1].pcolormesh(x7,xm,A7v.T,cmap='hot_r',vmin=1,vmax=100)
ax[0,1].set_title('Var. PSD')
ax[0,2].pcolormesh(x7,xm,A7r.T,cmap='jet',vmin=30,vmax=60)
ax[0,2].set_title('Mean PSD (rel. 1/f)')
ax[1,0].pcolormesh(x7,xm,B7m.T,cmap='jet',vmin=0,vmax=80)
ax[1,0].set_ylabel('Fiber B')
ax[1,0].set_xlabel('Distance (km)')
ax[1,1].pcolormesh(x7,xm,B7v.T,cmap='hot_r',vmin=1,vmax=100)
ax[1,1].set_xlabel('Distance (km)')
ax[1,2].pcolormesh(x7,xm,B7r.T,cmap='jet',vmin=30,vmax=60)
ax[1,2].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.suptitle('TERRA-SW Test 7 (6 m pulse, 9.6 m gauge - 2 kHz!)')
plt.tight_layout()
plt.savefig('TERRA_summary_7.png')

fig, ax = plt.subplots(7,2,sharex=True,sharey=True,figsize=(8,17))
ax[0,0].pcolormesh(x1,xm,(A1m-B1m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Test 1')
ax[0,1].pcolormesh(x1,xm,(A1v-B1v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[0,1].set_title('Var. PSD')
ax[1,0].pcolormesh(x2,xm,(A2m-B2m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[1,0].set_ylabel('Test 2')
ax[1,1].pcolormesh(x2,xm,(A2v-B2v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[2,0].pcolormesh(x3,xm,(A3m-B3m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[2,0].set_ylabel('Test 3')
ax[2,1].pcolormesh(x3,xm,(A3v-B3v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[3,0].pcolormesh(x4,xm,(A4m-B4m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[3,0].set_ylabel('Test 4')
ax[3,1].pcolormesh(x4,xm,(A4v-B4v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[4,0].pcolormesh(x5,xm,(A5m-B5m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[4,0].set_ylabel('Test 5')
ax[4,1].pcolormesh(x5,xm,(A5v-B5v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[5,0].pcolormesh(x6,xm,(A6m-B6m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[5,0].set_ylabel('Test 6')
ax[5,1].pcolormesh(x6,xm,(A6v-B6v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[6,0].pcolormesh(x7,xm,(A7m-B7m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[6,0].set_ylabel('Test 7')
im = ax[6,1].pcolormesh(x7,xm,(A7v-B7v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[6,1].set_xlabel('Distance (km)')
ax[6,0].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.subplots_adjust(right=0.8)
cbar_ax = fig.add_axes([0.85, 0.15, 0.05, 0.7])
fig.colorbar(im, cax=cbar_ax)
fig.suptitle('TERRA-SW Fiber A - Fiber B difference')
#plt.tight_layout()
plt.savefig('TERRA_summary_8.png')


fig, ax = plt.subplots(5,2,sharex=True,sharey=True,figsize=(8,17))
ax[0,0].pcolormesh(x1,xm,(A1m-A2m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[0,0].set_title('Fiber A')
ax[0,0].set_ylabel('Test 1 - Test 2')
ax[0,1].pcolormesh(x1,xm,(B1m-B2m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[0,1].set_title('Fiber B')
ax[1,0].pcolormesh(x2,xm,(A1m-A3m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[1,0].set_ylabel('Test 1 - Test 3')
ax[1,1].pcolormesh(x2,xm,(B1m-B3m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[2,0].pcolormesh(x3,xm,(A1m-A4m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[2,0].set_ylabel('Test 1 - Test 4')
ax[2,1].pcolormesh(x3,xm,(B1m-B4m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[3,0].pcolormesh(x4,xm,(A1m-A5m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[3,0].set_ylabel('Test 1 - Test 5')
ax[3,1].pcolormesh(x4,xm,(B1m-B5m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[4,0].pcolormesh(x5,xm,(A1m-A6m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[4,0].set_ylabel('Test 1 - Test 6')
ax[4,1].pcolormesh(x5,xm,(B1m-B6m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[4,0].set_xlabel('Distance (km)')
ax[4,1].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.subplots_adjust(right=0.8)
cbar_ax = fig.add_axes([0.85, 0.15, 0.05, 0.7])
fig.colorbar(im, cax=cbar_ax)
fig.suptitle('TERRA-SW mean PSD difference rel. Test 1')
plt.savefig('TERRA_summary_9.png')

fig, ax = plt.subplots(5,2,sharex=True,sharey=True,figsize=(8,17))
ax[0,0].pcolormesh(x1,xm,(A1v-A2v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[0,0].set_title('Fiber A')
ax[0,0].set_ylabel('Test 1 - Test 2')
ax[0,1].pcolormesh(x1,xm,(B1v-B2v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[0,1].set_title('Fiber B')
ax[1,0].pcolormesh(x2,xm,(A1v-A3v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[1,0].set_ylabel('Test 1 - Test 3')
ax[1,1].pcolormesh(x2,xm,(B1v-B3v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[2,0].pcolormesh(x3,xm,(A1v-A4v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[2,0].set_ylabel('Test 1 - Test 4')
ax[2,1].pcolormesh(x3,xm,(B1v-B4v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[3,0].pcolormesh(x4,xm,(A1v-A5v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[3,0].set_ylabel('Test 1 - Test 5')
ax[3,1].pcolormesh(x4,xm,(B1v-B5v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[4,0].pcolormesh(x5,xm,(A1v-A6v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[4,0].set_ylabel('Test 1 - Test 6')
ax[4,1].pcolormesh(x5,xm,(B1v-B6v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[4,0].set_xlabel('Distance (km)')
ax[4,1].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.subplots_adjust(right=0.8)
cbar_ax = fig.add_axes([0.85, 0.15, 0.05, 0.7])
fig.colorbar(im, cax=cbar_ax)
fig.suptitle('TERRA-SW var. PSD difference rel. Test 1')
plt.savefig('TERRA_summary_10.png')








plt.show()
