#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt

xm = np.load('xm.npy')
x = np.load('x.npy')

A1m = np.load('KKFL-S_A_test1_mean.npy')
A1v = np.load('KKFL-S_A_test1_vars.npy')
A1r = np.load('KKFL-S_A_test1_rate.npy')

B1m = np.load('KKFL-S_B_test1_mean.npy')
B1v = np.load('KKFL-S_B_test1_vars.npy')
B1r = np.load('KKFL-S_B_test1_rate.npy')

A2m = np.load('KKFL-S_A_test2_mean.npy')
A2v = np.load('KKFL-S_A_test2_vars.npy')
A2r = np.load('KKFL-S_A_test2_rate.npy')

B2m = np.load('KKFL-S_B_test2_mean.npy')
B2v = np.load('KKFL-S_B_test2_vars.npy')
B2r = np.load('KKFL-S_B_test2_rate.npy')

x = np.arange(A1m.shape[0])*100*6.38*1e-3

fig, ax = plt.subplots(2,3,sharex=True,sharey=True)
ax[0,0].pcolormesh(x,xm,A1m.T,cmap='jet',vmin=0,vmax=80)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Fiber A')
ax[0,1].pcolormesh(x,xm,A1v.T,cmap='hot_r',vmin=1,vmax=100)
ax[0,1].set_title('Var. PSD')
ax[0,2].pcolormesh(x,xm,A1r.T,cmap='jet',vmin=30,vmax=60)
ax[0,2].set_title('Mean PSD (rel. 1/f)')
ax[1,0].pcolormesh(x,xm,B1m.T,cmap='jet',vmin=0,vmax=80)
ax[1,0].set_ylabel('Fiber B')
ax[1,0].set_xlabel('Distance (km)')
ax[1,1].pcolormesh(x,xm,B1v.T,cmap='hot_r',vmin=1,vmax=100)
ax[1,1].set_xlabel('Distance (km)')
ax[1,2].pcolormesh(x,xm,B1r.T,cmap='jet',vmin=30,vmax=60)
ax[1,2].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.suptitle('KKFL-S Test 1 (10 m pulse, 17 m gauge)')
plt.tight_layout()
plt.savefig('KKFL-S_summary_1.png')

fig, ax = plt.subplots(2,3,sharex=True,sharey=True)
ax[0,0].pcolormesh(x,xm,A2m.T,cmap='jet',vmin=0,vmax=80)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Fiber A')
ax[0,1].pcolormesh(x,xm,A2v.T,cmap='hot_r',vmin=1,vmax=100)
ax[0,1].set_title('Var. PSD')
ax[0,2].pcolormesh(x,xm,A2r.T,cmap='jet',vmin=30,vmax=60)
ax[0,2].set_title('Mean PSD (rel. 1/f)')
ax[1,0].pcolormesh(x,xm,B2m.T,cmap='jet',vmin=0,vmax=80)
ax[1,0].set_ylabel('Fiber B')
ax[1,0].set_xlabel('Distance (km)')
ax[1,1].pcolormesh(x,xm,B2v.T,cmap='hot_r',vmin=1,vmax=100)
ax[1,1].set_xlabel('Distance (km)')
ax[1,2].pcolormesh(x,xm,B2r.T,cmap='jet',vmin=30,vmax=60)
ax[1,2].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.suptitle('KKFL-S Test 2 (17 m pulse, 24 m gauge)')
plt.tight_layout()
plt.savefig('KKFL-S_summary_2.png')

fig, ax = plt.subplots(2,2,sharex=True,sharey=True)
ax[0,0].pcolormesh(x,xm,(A1m-A2m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Fiber A')
ax[0,1].pcolormesh(x,xm,(A1v-A2v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[0,1].set_title('Var. PSD')
ax[1,0].pcolormesh(x,xm,(B1m-B2m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[1,0].set_xlabel('Distance (km)')
ax[1,0].set_ylabel('Fiber B')
im = ax[1,1].pcolormesh(x,xm,(B1v-B2v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[1,1].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.subplots_adjust(right=0.8)
cbar_ax = fig.add_axes([0.85, 0.15, 0.05, 0.7])
fig.colorbar(im, cax=cbar_ax)
fig.suptitle('KKFL-S Test 1 - Test 2 difference')
plt.savefig('KKFL-S_summary_3.png')

fig, ax = plt.subplots(2,2,sharex=True,sharey=True)
ax[0,0].pcolormesh(x,xm,(A1m-B1m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[0,0].set_title('Mean PSD')
ax[0,0].set_ylabel('Test 1')
ax[0,1].pcolormesh(x,xm,(A1v-B1v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[0,1].set_title('Var. PSD')
ax[1,0].pcolormesh(x,xm,(A2m-B2m).T,cmap='RdBu',vmin=-10,vmax=10)
ax[1,0].set_xlabel('Distance (km)')
ax[1,0].set_ylabel('Test 2')
im = ax[1,1].pcolormesh(x,xm,(A2v-B2v).T,cmap='RdBu',vmin=-10,vmax=10)
ax[1,1].set_xlabel('Distance (km)')
ax[0,0].set_yscale('log')
fig.subplots_adjust(right=0.8)
cbar_ax = fig.add_axes([0.85, 0.15, 0.05, 0.7])
fig.colorbar(im, cax=cbar_ax)
fig.suptitle('KKFL-S Fiber A - Fiber B difference')
plt.savefig('KKFL-S_summary_4.png')


plt.show()


